build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"

    - PYTHON: "C:\\Python33"

    - PYTHON: "C:\\Python34"

    - PYTHON: "C:\\Python35"


init:
  - "ECHO %PYTHON%"

install:
  - "%PYTHON%/Scripts/pip.exe install nose"
  - "%PYTHON%/Scripts/pip.exe install coverage"
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"

test_script:
  - "%PYTHON%/Scripts/nosetests"
